version: '2'
services:
    aicheyide-app:
        image: aicheyide
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://aicheyide-mysql:3306/aicheyide?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aicheyide-mysql:
        extends:
            file: mysql.yml
            service: aicheyide-mysql
